### ISSUE TITLE
Hex not up-to-date

### ISSUE THREAD

**Issue by morgz** [johantell/metatags#11]
hey . - not sure if you need to update hex but the latest version isn't available on it:
https://hex.pm/packages/metatags

Thanks

Dan

**Comment by johantell** [comment]
@morgz Thanks for pointing that out. I actually released 3.0 on hex but had to revert the release is I had introduced a bug I haven't yet had time to solve. I'll try to get to that in the coming days :)

**Comment by johantell** [comment]
@morgz I took the time to update it now so it's available on hex. 

In case you didn't notice there's a few really small _breaking_ changes that happened since `0.2.0`. 
You can read about them in the [CHANGELOG.md](https://github.com/johantell/metatags/blob/master/CHANGELOG.md#030)

**Comment by morgz** [comment]
Thanks Johan!
