### ISSUE TITLE
Bump to phoenix_html v4.0

### ISSUE THREAD

**Issue by PJUllrich** [johantell/metatags#134]
Hey there,

I like this library and would love to use it, but unfortunately, I'm on `phoenix_html: "~> 4.0.0"` which removed the `Phoenix.HTML.Tag` module that this library depends on. Do you have plans on upgrading anytime soon? It would be tricky to support both v3 and v4 of Phoenix.HTML at the same time though 🤔 Let me know if you want help :)

**Comment by johantell** [comment]
@PJUllrich I'm sooo sorry for not seeing this sooner. I must have some problem with my github notifications. Either way, I appreciate you reaching about the error. I did notice it myself a few weeks ago and released a new version that will remove the dependency on `Phoenix.HTML` but I suppose it was about 8 months too late. I'll release a new version in case you still want to use the library, If so, please let me know if you consider it solved :). If not I'm always open for more issues or PR's 

Again, sorry for the wait, the only decent excuse I have is that my first child was born around the time of your issue

**Comment by PJUllrich** [comment]
Thank you! 😊

**Comment by johantell** [comment]
Thanks! I'll close this ticket now, let me know if the problem persists
