### ISSUE TITLE
Update to phoenix_html version 3

### ISSUE THREAD

**Issue by brettinternet** [johantell/metatags#53]
Hi, you have a great solution here. Looks like compatibility with `phoenix_html` version 3 is required for usage with the latest phoenix builds.

**Comment by johantell** [comment]
Sorry for the late response @brettinternet. For some reason I didn't get a notification. I'll get to do the update later this week 👍

**Comment by qborisb** [comment]
This PR updates phoenix_html to 3.1 and it seems to work!
https://github.com/johantell/metatags/pull/60

**Comment by johantell** [comment]
Thanks @qborisb for your participation, I'm publishing v0.3.2 which should be usable with phoenix_html v3+ now
